CREATE TABLE IF NOT EXISTS movie_extras (
	id SERIAL PRIMARY KEY,
	"name" VARCHAR(50) UNIQUE NOT NULL,
	"description" TEXT,
	duration INTEGER NOT NULL,
	price INTEGER NOT NULL,
	categories VARCHAR(50) ARRAY NOT NULL,
	discount INTEGER NOT NULL DEFAULT 0,
	stock INTEGER NOT NULL DEFAULT 0
);